#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 5
bspc monitor DP-0 -d 1 2 3
bspc monitor DP-2 -d 4

#config
bspc config window_gap             10
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true
bspc config border_width 0
bspc config top_padding 25

# startup
~/.config/polybar/./launch.sh
feh --bg-fill $HOME/.config/wallpapers/3.jpg
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
setxkbmap "us,cz(qwerty)" -option grp:rwin_toggle
unclutter &
