#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 5
bspc monitor DP-0 -d 1 2 3
bspc monitor DP-2 -d 4

# General
bspc config window_gap             10
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

# Coloring
bspc config border_width 1
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#000000"
bspc config focused_border_color	"#000000"
bspc config presel_feedback_color	"#000000"

bspc config top_padding 25

# Startup
~/.config/polybar/./launch.sh
feh --bg-fill $HOME/.config/wallpapers/1.jpg
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
setxkbmap "us,cz(qwerty)" -option grp:rctrl_toggle
unclutter &
